
DATA_STANDARD_SCALER="StandardScaler"
DATA_ROBUST_SCALER ="RobustScaler"
DATA_NORMALIZER_SCALER ="Normalizer"
DATA_MIN_MAX_SCALER="MinMaxScaler"
DATA_MAX_ABS_SCALER="MaxAbsScaler"

FILE_NAME = "spine.csv"
TARGET_COLUMN_NAME = "class"

PERCENT_TEST_SIZE = 40
HIDDEN_LAYER_NEURON_SIZES = (20, 20, 20)
ACTIVATION_FUNCTION = "identity"
SOLVER_OPTIMIZATION = "adam"
MAXIMUM_ITERATION = 1500
RANDOM_STATE = 1

ENCODING_LATIN1=None